bamfile: #/home/antonl/projects/LUSTRE_reanalysis/230202_LUSTRE_PN_NeuN_extra_sequencing/UNK_discond_merged.sorted.bam
cellfile: #/home/antonl/projects/LUSTRE_reanalysis/230202_LUSTRE_PN_NeuN_extra_sequencing/Post_Natal_cells.txt
