cbc_to_donor:
  AAAGGAGTAGGA: DONOR_A
  AAGCTGGATCTG: DONOR_A
  AAGGAGTATGCA: DONOR_A
  AATCATATAACA: DONOR_A
  AATGCTTAACCC: DONOR_A
  AATTCGATTTTT: DONOR_A
  ACGCAGGCGTTG: DONOR_A
  ACGGTTATAATT: DONOR_A
  ACTTAACTTTCA: DONOR_A
  AGACACACTCTT: DONOR_A
  AGCGGAGCCTTA: DONOR_A
  AGCTGGCTAAGC: DONOR_A
  AGCTTTTCTATT: DONOR_A
  AGTTGCAGTCGT: DONOR_A
  ATAAGGAATAGG: DONOR_A
  ATACCCATTGAC: DONOR_A
  ATCCAGGTAATG: DONOR_A
  ATCCTAAACTTC: DONOR_A
  ATCTGATTTTTA: DONOR_A
  ATGAAGGATTCA: DONOR_A
  ATGAATCTGTGT: DONOR_A
  ATTGATTCCCGC: DONOR_A
  ATTGTTGCATCG: DONOR_A
  CAAGTCGTGTTA: DONOR_A
  CACACTCTCCTT: DONOR_A
  CACCCACGCATA: DONOR_A
  CACGCACAGACG: DONOR_A
  CACTTTCGGGAA: DONOR_A
  CAGCCATGCAGA: DONOR_A
  CAGCGGCCAGGA: DONOR_A
  CAGGACTGCGAA: DONOR_A
  CAGGTGCAACCC: DONOR_A
  CATAATCTGCAT: DONOR_A
  CATGAAAGTCAC: DONOR_A
  CCAATCTCAGAA: DONOR_A
  CCACTGTGCGAC: DONOR_A
  CCATGCGGCAAT: DONOR_A
  CCGCTAAGACGG: DONOR_A
  CCTTAGGTCCAA: DONOR_A
  CGAAAGATTAAG: DONOR_A
  CGAGCAGATTAC: DONOR_A
  CGGCCACTTAAG: DONOR_A
  CGGCCTACCAGG: DONOR_A
  CGGTAGACGCCT: DONOR_A
  CGGTTTCCGTTA: DONOR_A
  CTGCGAGTGTGA: DONOR_A
  CTGCGGGGGTGT: DONOR_A
  CTGTTTTGGATT: DONOR_A
  CTTCGATTCGGA: DONOR_A
  CTTGCCCTCGTG: DONOR_A
  GAATACAAGGGC: DONOR_B
  GACAGGTACAAG: DONOR_B
  GACCCGTGAAAG: DONOR_B
  GACGACAACCAG: DONOR_B
  GACGCACTGGTT: DONOR_B
  GCACTGTAGTCG: DONOR_B
  GCCACTGGAGAC: DONOR_B
  GCCGCTTATACG: DONOR_B
  GCCGGACGAAGT: DONOR_B
  GCGCCCTACCGC: DONOR_B
  GCGCGCGCCAAA: DONOR_B
  GCGGCGCGATGG: DONOR_B
  GCTATGTAGCCT: DONOR_B
  GCTGTATATCAC: DONOR_B
  GCTTGAAAACTA: DONOR_B
  GGACTGGGAGGT: DONOR_B
  GGCAGCCTGCCC: DONOR_B
  GGGCAACTGTTA: DONOR_B
  GGTACCTAACCC: DONOR_B
  GGTCGACACCTA: DONOR_B
  GGTTAAATGTAA: DONOR_B
  GTAACGTGCAAA: DONOR_B
  GTCGGTTAACGG: DONOR_B
  GTTCGCGCGACT: DONOR_B
  GTTCTCTGCATA: DONOR_B
  TAAGTGGGCACG: DONOR_B
  TAGGCACCGTCG: DONOR_B
  TAGGTCGTTCAG: DONOR_B
  TCAATGTGGTCG: DONOR_B
  TCGCTCCAGCGT: DONOR_B
  TCGGCTTAGCTG: DONOR_B
  TCGGGATAAGAT: DONOR_B
  TCGGGTAAGAAA: DONOR_B
  TCTGCGGGAGCT: DONOR_B
  TGAGTATTGCTA: DONOR_B
  TGGCACCCGAAG: DONOR_B
  TGGGTGTGCCAG: DONOR_B
  TGGGTTAACCAT: DONOR_B
  TGGTGATCGTAA: DONOR_B
  TGTGAACTTTTA: DONOR_B
  TGTGACATTTCA: DONOR_B
  TGTGGAACAAAC: DONOR_B
  TGTTAGGGCGAC: DONOR_B
  TTAACGTCGAGG: DONOR_B
  TTACATTACGCT: DONOR_B
  TTATGTGCGTCT: DONOR_B
  TTCCATCCATAC: DONOR_B
  TTCTCTGTCCGT: DONOR_B
  TTGTGCGAGAAT: DONOR_B
  TTGTTTCTAGCG: DONOR_B
