project: 230818_LUSTRExSS3_RUN
idx_fastq:
samplesheet: samplesheet.csv
expected_barcodes: barcodes.txt
fasta_file: ../reference_genomes/hg38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
KNR_file: ../resources/nonref.collection.hg38.chr.L1.bed
old_KNR_file: ../resources/KNR_chr.bed
KR_file: ../resources/KR_chr.bed

threads: 50

samtools: samtools
bedtools: bedtools
bwa: bwa
fastp: fastp
demultiplex_fastq:
split_barcoded_bam: ../split_barcoded_bam/target/release/split_barcoded_bam

